In [3]:
import numpy as np

In [4]:
a = np.array([[1,2,3],
              [4,5,6]])

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a.shape

(2, 3)

In [8]:
a = np.array([1,2,3,4,5,6])

In [9]:
a

array([1, 2, 3, 4, 5, 6])

In [10]:
a[0]

np.int64(1)

In [12]:
a[0]=10

In [13]:
a

array([10,  2,  3,  4,  5,  6])

In [15]:
a[2:]

array([3, 4, 5, 6])

In [16]:
a[:2]

array([10,  2])

In [18]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [19]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
a[1,1]

np.int64(6)

In [22]:
a[1,3]

np.int64(8)

In [23]:
a.ndim

2

In [27]:
len(a)

3

In [24]:
a.shape

(3, 4)

In [25]:
a.size

12

In [28]:
import math

math.prod(a.shape)

12

In [29]:
type(a)

numpy.ndarray

In [30]:
a.dtype

dtype('int64')

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [32]:
np.ones(4)

array([1., 1., 1., 1.])

In [33]:
np.empty(5)

array([5.27888459e-310, 0.00000000e+000, 5.27888463e-310, 5.27888467e-310,
       0.00000000e+000])

In [37]:
np_array_10 = np.arange(10)
np_array_10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
type(np_array_10)

numpy.ndarray

In [39]:
np_array_10_list = list(np_array_10)
np_array_10_list

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [40]:
type(np_array_10_list)

list

In [41]:
np_array_10.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
emp_list = []

n=0
while n < 10:
    emp_list.append(n)
    n+=1

print(emp_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [42]:
np.arange(3,15,4)

array([ 3,  7, 11])

Detyra: Nje varg i numrave tek mes 10 dhe 20-it.

In [44]:
np.arange(11,20,2)

array([11, 13, 15, 17, 19])

In [47]:
np.linspace(0,1,101
            )

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [48]:
x = np.ones(2, dtype=np.int8)
x

array([1, 1], dtype=int8)

np.ones, np.zero, np.empty, np.arange, np.linspace -> generate default valued arrays

In [49]:
np.ones(5) + np.empty(5)

array([1., 1., 1., 1., 1.])

In [50]:
def_list = [2,1,6,4,10,3]

In [51]:
arr = np.array(def_list)
arr

array([ 2,  1,  6,  4, 10,  3])

In [52]:
np.sort(arr)

array([ 1,  2,  3,  4,  6, 10])

In [53]:
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,10])

In [55]:
np.concatenate((arr_1, arr_2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

In [61]:
x.shape

(2, 2)

In [62]:
y.shape

(1, 2)

In [65]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
arr_3d = np.array([[
                    [1,2,3],
                    [4,5,6],
                    [7,8,9]
                    ],
                    [
                    [1,2,3],
                    [4,5,6],
                    [7,8,9]
                    ]])

In [70]:
arr_3d.ndim

3

In [71]:
arr_3d.shape

(2, 3, 3)

In [73]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [74]:
a.shape

(6,)

In [78]:
b = a.reshape(2,3)

In [79]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [80]:
b.ndim

2

In [82]:
np.arange(2,10,5)

array([2, 7])

In [83]:
a = np.array([
        np.arange(0,6,2),
        np.arange(6,12,2),
        np.arange(12,18,2)
])

In [84]:
a 

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [86]:
a_2 = a * 2
a_2

array([[ 0,  4,  8],
       [12, 16, 20],
       [24, 28, 32]])

In [88]:
mask_10 = a < 10

In [89]:
a[mask_10]

array([0, 2, 4, 6, 8])

In [90]:
a_2[mask_10]

array([ 0,  4,  8, 12, 16])

In [93]:
a_1 = a + 1

In [96]:
a_1

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [95]:
a_1[a_1%2==0]

array([], dtype=int64)

In [97]:
mask_2_7 = (a>=2)&(a<=7)

In [98]:
a[mask_2_7]

array([2, 4, 6])

In [99]:
mask_5_10 = (a<=5)|(a>=10)
mask_5_10

array([[ True,  True,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [100]:
a[mask_5_10]

array([ 0,  2,  4, 10, 12, 14, 16])

In [104]:
b = np.nonzero(mask_5_10)
b

(array([0, 0, 0, 1, 2, 2, 2]), array([0, 1, 2, 2, 0, 1, 2]))

In [110]:
zip(b[0],b[1])

In [113]:
for cord in zip(b[0].tolist(),b[1].tolist()):
    print(cord)

(0, 0)
(0, 1)
(0, 2)
(1, 2)
(2, 0)
(2, 1)
(2, 2)


In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
even_mask = a%2==0

a_1 = a[even_mask]
a_1 

array([0, 2, 4, 6, 8])

In [6]:
odd_mask = a%2==1

a_2 = a[odd_mask]
a_2

array([1, 3, 5, 7, 9])

In [7]:
array_1 = np.array(
    [
        [1,1],
        [2,2]
    ]
)

array_2 = np.array(
    [
        [3,3],
        [4,4]
    ]
)

In [8]:
array_v = np.vstack((array_1,array_2))
array_v

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [9]:
array_h = np.hstack((array_1,array_2))
array_h

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [10]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [11]:
x_1, x_2, x_3 = np.hsplit(x,3)

In [12]:
x_1

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [13]:
x_2

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [14]:
x_1_v, x_2_v = np.vsplit(x,2)
x_1_v

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [20]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [21]:
b1 = a.copy()[0,:] # if you want to have a copy use .copy() method
b1

array([1, 2, 3, 4])

In [22]:
b1[0] = 100
b1

array([100,   2,   3,   4])

In [23]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])